# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eb04f90a7981e3b024f4b3ec6d0b262d243338f501bd7a7f2404704a5365de5d3ed71cfffdde218ec0a191b0f3c46a2631dc00bd1b2adc3724a799790e2abe1

test:
  secret_key_base: dcfd128ebe8e53f8f313f03aeccace7153ad00bdaf3e3793422a256b766d355e3d25c73a7ec5d527fcb565407222c61b65b88109e2e6d5bb79a995118aac0ef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
